# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  generative1_config = debug

else ifeq ($(config),release)
  generative1_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := generative1

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

generative1:
ifneq (,$(generative1_config))
	@echo "==== Building generative1 ($(generative1_config)) ===="
	@${MAKE} --no-print-directory -C . -f generative1.make config=$(generative1_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f generative1.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   generative1"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"